#!/usr/bin/env bash
#
# Driver for the bhs-controlroom test bench.
# Equivalent to bench.ps1, for Linux, macOS and Git Bash.
#
# Usage: bash bench.sh <command>   (or ./bench.sh once it is executable)
#
#   up                     start the stack and wait for everything to answer
#   console | dashboard    open the console, or the Grafana dashboard
#   scenario <name>        apply a scenario
#   verify                 run every scenario and check both sources
#   status                 state of the services and of both sources
#   test                   unit tests of the simulation model
#   package                self-contained copy of the bench
#   stop | start           pause and resume, without losing the data
#   logs | down            logs; stop and drop the volumes

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT"

# Git Bash rewrites /opt/... into a Windows path before handing it to
# docker exec. Without this, sqlcmd cannot be found inside the container.
case "$(uname -s)" in
    MINGW*|MSYS*|CYGWIN*) export MSYS_NO_PATHCONV=1 ;;
esac

# `command -v` is not enough: on Windows, python3 is often a Microsoft Store
# stub that sits in PATH but runs nothing. The only reliable test is to make
# it execute something.
detect_python() {
    local candidate
    for candidate in python3 python py; do
        if command -v "$candidate" >/dev/null 2>&1 \
           && "$candidate" -c 'import sys' >/dev/null 2>&1; then
            echo "$candidate"
            return 0
        fi
    done
    return 1
}

PYTHON="$(detect_python || true)"
if [ -z "$PYTHON" ]; then
    echo "python is required (dashboard preparation, port selection)." >&2
    exit 1
fi

SCENARIOS="normal morning_rush system_jam night_idle tracker_outage api_outage phantom_storm"

step() { printf '\033[36m==> %s\033[0m\n' "$1"; }
info() { printf '    \033[90m%s\033[0m\n' "$1"; }
warn() { printf '\033[33m    %s\033[0m\n' "$1"; }

setting() {
    local key="$1" fallback="${2-}"
    if [ -f .env ]; then
        local value
        value="$(grep -m1 "^${key}=" .env 2>/dev/null | cut -d= -f2- | tr -d '\r' || true)"
        [ -n "$value" ] && { echo "$value"; return; }
    fi
    echo "$fallback"
}

reload_ports() {
    PORT_GRAFANA="$(setting GRAFANA_PORT 3000)"
    PORT_API="$(setting API_PORT 8080)"
    PORT_CONSOLE="$(setting CONSOLE_PORT 8090)"
    URL_GRAFANA="http://localhost:${PORT_GRAFANA}"
    URL_CONSOLE="http://localhost:${PORT_CONSOLE}"
    URL_DASHBOARD="${URL_GRAFANA}/d/bhs-controlroom/salle-de-controle?kiosk&refresh=5s"
}
reload_ports

# --------------------------------------------------------------------------
# Setup
# --------------------------------------------------------------------------

# SQL Server rejects weak passwords: at least one upper case, one lower case,
# one digit and one symbol. Symbols are deliberately restricted, so that
# nothing gets reinterpreted on the way by bash, sqlcmd or T-SQL.
#
# Generated by Python rather than in shell: `shuf` is a GNU tool, missing on
# macOS, and this script has to behave the same on all three systems.
password() {
    "$PYTHON" - <<'PY'
import secrets, string

SYMBOLS = "#%+=@-"
alphabet = string.ascii_letters + string.digits + SYMBOLS

while True:
    candidate = "".join(secrets.choice(alphabet) for _ in range(24))
    if (any(c.isupper() for c in candidate) and any(c.islower() for c in candidate)
            and any(c.isdigit() for c in candidate) and any(c in SYMBOLS for c in candidate)):
        print(candidate)
        break
PY
}

free_port() {
    "$PYTHON" - "$1" <<'PY'
import socket, sys
start = int(sys.argv[1])
for port in range(start, start + 21):
    with socket.socket() as probe:
        if probe.connect_ex(("127.0.0.1", port)) != 0:
            print(port)
            break
else:
    print(start)
PY
}

init_env() {
    if [ -f .env ]; then
        info ".env already present, kept (Grafana ${PORT_GRAFANA}, console ${PORT_CONSOLE})"
        return
    fi
    step "Generating .env (random passwords, local machine)"
    local g a c q
    g="$(free_port 3000)"; a="$(free_port 8080)"
    c="$(free_port 8090)"; q="$(free_port 1433)"
    [ "$g" != "3000" ] && info "Port 3000 busy, Grafana will be published on $g" || true
    [ "$c" != "8090" ] && info "Port 8090 busy, the console will be published on $c" || true

    cat > .env <<EOF
# Generated by bench.sh. Local bench: ports published on 127.0.0.1 only.
MSSQL_SA_PASSWORD=$(password)
SQL_READONLY_PASSWORD=$(password)
GRAFANA_PORT=$g
API_PORT=$a
CONSOLE_PORT=$c
SQL_PORT=$q
EOF
    reload_ports
}

# sqlcmd runs inside the container: no SQL client to install on the host.
# The server image ships sqlcmd 18, which encrypts by default, hence -C.
sql() {
    local pwd_sa
    pwd_sa="$(setting MSSQL_SA_PASSWORD)"
    docker exec bhs-sqlserver /opt/mssql-tools18/bin/sqlcmd \
        -S localhost -U sa -P "$pwd_sa" -C -d bhs -b "$@"
}

sql_probe() {
    sql -h -1 -W -i /sql/probe.sql 2>/dev/null | head -1 | tr -d '\r' || echo "?;?;?"
}

console_post() {
    local path="$1" body="$2" token
    token="$(setting CONSOLE_TOKEN '')"
    if [ -n "$token" ]; then
        curl -sf -X POST -H 'Content-Type: application/json' \
             -H "X-Console-Token: ${token}" -d "$body" "${URL_CONSOLE}${path}"
    else
        curl -sf -X POST -H 'Content-Type: application/json' \
             -d "$body" "${URL_CONSOLE}${path}"
    fi
}

# HTTP status only. `-o /dev/null` is avoided on purpose: under Git Bash,
# MSYS_NO_PATHCONV stops the path from being translated, curl fails to write
# and reports an error even though the request went through perfectly.
http_status() {
    local output
    output="$(curl -s -w '\n%{http_code}' --max-time 5 "$1" 2>/dev/null | tail -n1)"
    echo "${output:-000}"
}

wait_for() {
    local url="$1" name="$2" attempts="${3:-90}"
    step "Waiting for $name"
    local n=1
    while [ "$n" -le "$attempts" ]; do
        # Redirect from the shell, not from curl (-o): see http_status.
        if curl -sf --max-time 3 "$url" >/dev/null 2>&1; then
            info "$name answered after $n attempt(s)"
            return 0
        fi
        sleep 2
        n=$((n + 1))
    done
    warn "$name never answered; see bash bench.sh logs"
    return 1
}

open_url() {
    if command -v xdg-open >/dev/null 2>&1; then xdg-open "$1" >/dev/null 2>&1 &
    elif command -v open >/dev/null 2>&1; then open "$1" >/dev/null 2>&1 &
    elif command -v powershell.exe >/dev/null 2>&1; then powershell.exe -NoProfile -Command "Start-Process '$1'" >/dev/null 2>&1 || true
    else info "Open in a browser: $1"; return; fi
    info "$1"
}

# --------------------------------------------------------------------------
# Commands
# --------------------------------------------------------------------------

cmd_up() {
    init_env

    step "Preparing the delivered dashboard for provisioning"
    "$PYTHON" scripts/prepare-dashboard.py

    step "Starting the stack (the first run downloads ~2 GB)"
    docker compose up -d --wait --remove-orphans

    wait_for "${URL_GRAFANA}/api/health" "Grafana (including the Infinity plugin install)" || true
    wait_for "${URL_CONSOLE}/health" "the console" 30 || true

    echo
    printf '\033[32mConsole   : %s\033[0m\n' "$URL_CONSOLE"
    printf '\033[32mDashboard : %s\033[0m\n' "$URL_DASHBOARD"
    echo
    info "Check that everything answers: bash bench.sh verify"
}

cmd_scenario() {
    local name="${1-}"
    if [ -z "$name" ] || ! echo " $SCENARIOS " | grep -q " $name "; then
        echo "Available scenarios:"
        for s in $SCENARIOS; do echo "    $s"; done
        return 1
    fi
    step "Applying scenario $name"
    console_post /api/scenario "{\"name\":\"$name\"}" \
        | "$PYTHON" -c 'import json,sys; d=json.load(sys.stdin)["derived"]; print("    bags={} dwell={} banner={} phantoms/h={}".format(d["bags_in_system"], d["avg_dwell_minutes"], d["expected_banner"], d["phantoms_per_hour"]))'
    info "The dashboard follows on its next refresh (5 s)"
}

# Automated check: every scenario is applied, then both sources are queried
# to confirm they tell the same story as the console.
cmd_verify() {
    local expectations freshness active phantoms status failures=0
    # scenario:expected freshness:expected active bags:expected API status
    expectations="normal:OK:142:200
morning_rush:OK:377:200
system_jam:OK:577:200
night_idle:IDLE:0:200
tracker_outage:STALE:142:200
api_outage:OK:142:503"

    step "Checking the scenarios (about 90 s)"
    printf '    %-16s %-8s %-8s %-8s %s\n' SCENARIO BANNER ACTIVE API RESULT

    while IFS=: read -r name want_fresh want_active want_status; do
        console_post /api/scenario "{\"name\":\"$name\"}" > /dev/null
        sleep 12
        IFS=';' read -r freshness active phantoms <<< "$(sql_probe)"
        status="$(http_status "http://localhost:${PORT_API}/api/v1/status")"

        # The stock takes a few ticks to fill up: allow a small drift.
        local drift=$(( active > want_active ? active - want_active : want_active - active ))
        if [ "$freshness" = "$want_fresh" ] && [ "$drift" -le 12 ] && [ "$status" = "$want_status" ]; then
            printf '    %-16s %-8s %-8s %-8s \033[32mOK\033[0m\n' "$name" "$freshness" "$active" "$status"
        else
            printf '    %-16s %-8s %-8s %-8s \033[31mFAILED\033[0m (expected %s / %s / %s)\n' \
                   "$name" "$freshness" "$active" "$status" "$want_fresh" "$want_active" "$want_status"
            failures=$((failures + 1))
        fi
    done <<< "$expectations"

    # Use case 1: phantoms must pile up, then the purge must clear them.
    step "Checking the phantom-bag defect (use case 1)"
    console_post /api/scenario '{"name":"phantom_storm"}' > /dev/null
    sleep 8
    local before after
    before="$(sql_probe | cut -d';' -f3)"
    sleep 25
    after="$(sql_probe | cut -d';' -f3)"
    if [ "$after" -gt "$before" ]; then
        printf '    build-up %s -> %s phantoms       \033[32mOK\033[0m\n' "$before" "$after"
    else
        printf '    build-up %s -> %s phantoms       \033[31mFAILED\033[0m\n' "$before" "$after"
        failures=$((failures + 1))
    fi

    console_post /api/state '{"phantom_bug":"fixed"}' > /dev/null
    console_post /api/purge-phantoms '{}' > /dev/null
    sleep 10
    local left
    left="$(sql_probe | cut -d';' -f3)"
    if [ "$left" -eq 0 ]; then
        printf '    purge -> %s phantom left         \033[32mOK\033[0m\n' "$left"
    else
        printf '    purge -> %s phantoms left        \033[31mFAILED\033[0m\n' "$left"
        failures=$((failures + 1))
    fi

    console_post /api/scenario '{"name":"normal"}' > /dev/null
    echo
    if [ "$failures" -eq 0 ]; then
        printf '\033[32mAll green. Bench back to nominal.\033[0m\n'
    else
        printf '\033[31m%s check(s) failed.\033[0m\n' "$failures"
        return 1
    fi
}

cmd_status() {
    docker compose ps
    step "Console"
    curl -sf "${URL_CONSOLE}/api/state" 2>/dev/null \
        | "$PYTHON" -c 'import json,sys; d=json.load(sys.stdin); s,v=d["settings"],d["derived"]; print("    scenario={} rate={} b/h dwell={} min bags={} banner={}".format(s["scenario"], s["arrival_rate"], s["dwell_minutes"], v["bags_in_system"], v["expected_banner"]))' \
        || warn "Console unreachable"

    step "Mocked API"
    curl -sf "http://localhost:${PORT_API}/api/v1/status" 2>/dev/null | sed 's/^/    /' \
        || info "API in simulated outage, or unreachable"

    step "SQL state (queries 1, 4 and 5 of queries.sql)"
    sql -i /sql/inspect.sql 2>/dev/null | tail -4 || warn "SQL unreachable"
}

cmd_package() {
    local target="dist/test-bench"
    step "Self-contained copy into ${ROOT}/${target}"
    rm -rf dist
    mkdir -p "$target"

    for item in console mock-api sql grafana/provisioning scripts tests \
                docker-compose.yml bench.ps1 bench.sh \
                .env.example README.md; do
        [ -e "$item" ] || continue
        mkdir -p "$target/$(dirname "$item")"
        cp -r "$item" "$target/$item"
    done

    # The delivered dashboard travels with the bench: prepare-dashboard.py
    # falls back on it once the use case 2 folder is no longer next door.
    if [ -f "../use-case-2-dashboard/solution/dashboard.json" ]; then
        mkdir -p "$target/dashboard"
        cp "../use-case-2-dashboard/solution/dashboard.json" "$target/dashboard/bhs-controlroom.source.json"
        info "dashboard.json embedded"
    fi

    find "$target" -name '__pycache__' -type d -prune -exec rm -rf {} + 2>/dev/null || true
    info "Neither .env nor state/ is copied: both get regenerated."
    echo
    printf '\033[32mReady: %s/%s\033[0m\n' "$ROOT" "$target"
    info "Run bash bench.sh up there, exactly as here."
}

case "${1:-status}" in
    up)        cmd_up ;;
    stop)      step "Pausing (data is kept)"
               docker compose stop
               info "Resume with: bash bench.sh start" ;;
    start)     step "Resuming the stack"
               # init is deliberately left out: it has already done its job,
               # running it again would re-seed the database for nothing.
               docker compose start sqlserver mock-api console simulator grafana
               wait_for "${URL_CONSOLE}/health" "the console" 45 || true
               info "Console: ${URL_CONSOLE}" ;;
    down)      step "Stopping the stack and dropping the volumes"; docker compose down -v ;;
    console)   open_url "$URL_CONSOLE" ;;
    dashboard) open_url "$URL_DASHBOARD" ;;
    scenario)  cmd_scenario "${2-}" ;;
    verify)    cmd_verify ;;
    status)    cmd_status ;;
    test)      step "Unit tests of the simulation model"; "$PYTHON" -m pytest tests -q ;;
    package)   cmd_package ;;
    logs)      docker compose logs --tail 60 ;;
    *)         sed -n '3,17p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//' ;;
esac
