<#
.SYNOPSIS
    Driver for the bhs-controlroom test bench.

.DESCRIPTION
    Starts the Docker stack (SQL Server 2019, mocked API, simulator, console
    and Grafana 9.5.15 + Infinity), and drives the scenarios from the command
    line when opening the web console is not wanted.

.EXAMPLE
    .\bench.ps1 up                    # start and wait for everything to answer
    .\bench.ps1 console               # open the simulation console
    .\bench.ps1 dashboard             # open the Grafana dashboard
    .\bench.ps1 scenario phantom_storm
    .\bench.ps1 verify                # run every scenario and check both sources
    .\bench.ps1 status
    .\bench.ps1 test                  # unit tests of the model
    .\bench.ps1 package               # self-contained copy of the bench
    .\bench.ps1 down
#>

[CmdletBinding()]
param(
    [Parameter(Position = 0)]
    [ValidateSet('up', 'stop', 'start', 'down', 'console', 'dashboard',
                 'scenario', 'verify', 'status', 'logs', 'test', 'package')]
    [string]$Action = 'status',

    [Parameter(Position = 1)]
    [string]$Name
)

$ErrorActionPreference = 'Stop'
$root = $PSScriptRoot

function Get-Setting([string]$key, [string]$fallback) {
    $file = Join-Path $root '.env'
    if (Test-Path $file) {
        $line = Get-Content $file | Where-Object { $_ -like "$key=*" } | Select-Object -First 1
        if ($line) { return ($line -replace "^$key=", '').Trim() }
    }
    return $fallback
}

$portGrafana = Get-Setting 'GRAFANA_PORT' '3000'
$portApi = Get-Setting 'API_PORT' '8080'
$portConsole = Get-Setting 'CONSOLE_PORT' '8090'
$urlGrafana = "http://localhost:$portGrafana"
$urlConsole = "http://localhost:$portConsole"
$urlDashboard = "$urlGrafana/d/bhs-controlroom/salle-de-controle?kiosk&refresh=5s"

$SCENARIOS = @('normal', 'morning_rush', 'system_jam', 'night_idle',
               'tracker_outage', 'api_outage', 'phantom_storm')

function Write-Step($message) { Write-Host "==> $message" -ForegroundColor Cyan }
function Write-Detail($message) { Write-Host "    $message" -ForegroundColor DarkGray }

# SQL Server rejects weak passwords, and there is no reason to hard-code one
# in a file that ends up in version control.
function New-Password {
    $classes = @(
        (65..90),    # A-Z
        (97..122),   # a-z
        (48..57),    # 0-9
        # Symbols deliberately restricted: no ! no ? no ' , which would get
        # reinterpreted along the way by bash, sqlcmd or T-SQL.
        (35, 37, 43, 45, 61, 64)
    )
    $characters = foreach ($class in $classes) { foreach ($n in 1..6) { [char](Get-Random -InputObject $class) } }
    return -join ($characters | Sort-Object { Get-Random })
}

# First free port from the wanted one: 3000 and 8080 are frequently taken by
# another project on the machine.
function Get-FreePort([int]$wanted) {
    foreach ($port in $wanted..($wanted + 20)) {
        $busy = Get-NetTCPConnection -State Listen -LocalPort $port -ErrorAction SilentlyContinue
        if (-not $busy) { return $port }
    }
    return $wanted
}

function Initialize-Env {
    $envFile = Join-Path $root '.env'
    if (Test-Path $envFile) {
        Write-Detail ".env already present, kept (Grafana $portGrafana, console $portConsole)"
        return
    }
    Write-Step 'Generating .env (random passwords, local machine)'
    $pGrafana = Get-FreePort 3000
    $pApi = Get-FreePort 8080
    $pConsole = Get-FreePort 8090
    $pSql = Get-FreePort 1433
    foreach ($pair in @(@(3000, $pGrafana, 'Grafana'), @(8080, $pApi, 'the API'), @(8090, $pConsole, 'the console'))) {
        if ($pair[0] -ne $pair[1]) { Write-Detail "Port $($pair[0]) busy, $($pair[2]) will be published on $($pair[1])" }
    }
    @(
        '# Generated by bench.ps1. Local bench: ports published on 127.0.0.1 only.',
        "MSSQL_SA_PASSWORD=$(New-Password)",
        "SQL_READONLY_PASSWORD=$(New-Password)",
        "GRAFANA_PORT=$pGrafana",
        "API_PORT=$pApi",
        "CONSOLE_PORT=$pConsole",
        "SQL_PORT=$pSql"
    ) | Out-File -FilePath $envFile -Encoding utf8

    $script:portGrafana = $pGrafana
    $script:portConsole = $pConsole
    $script:urlGrafana = "http://localhost:$pGrafana"
    $script:urlConsole = "http://localhost:$pConsole"
    $script:urlDashboard = "$script:urlGrafana/d/bhs-controlroom/salle-de-controle?kiosk&refresh=5s"
}

# sqlcmd runs inside the container: no SQL client to install on the host.
# The server image ships sqlcmd 18, which encrypts by default, hence -C.
function Invoke-Sql([string]$file) {
    $password = (Get-Content (Join-Path $root '.env') |
        Where-Object { $_ -like 'MSSQL_SA_PASSWORD=*' }) -replace '^MSSQL_SA_PASSWORD=', ''
    docker exec bhs-sqlserver /opt/mssql-tools18/bin/sqlcmd `
        -S localhost -U sa -P $password -C -d bhs -b -i "/sql/$file"
    if ($LASTEXITCODE -ne 0) { throw "$file failed (exit code $LASTEXITCODE)" }
}

function Invoke-Console([string]$path, $body) {
    $headers = @{ 'Content-Type' = 'application/json' }
    $token = Get-Setting 'CONSOLE_TOKEN' ''
    if ($token) { $headers['X-Console-Token'] = $token }
    return Invoke-RestMethod -Uri "$urlConsole$path" -Method Post `
        -Headers $headers -Body (ConvertTo-Json $body) -TimeoutSec 10
}

function Wait-Service([string]$url, [string]$name, [int]$attempts = 90) {
    Write-Step "Waiting for $name"
    foreach ($attempt in 1..$attempts) {
        try {
            $response = Invoke-WebRequest -Uri $url -UseBasicParsing -TimeoutSec 3
            if ($response.StatusCode -eq 200) {
                Write-Detail "$name answered after $attempt attempt(s)"
                return $true
            }
        } catch {
            Start-Sleep -Seconds 2
        }
    }
    Write-Warning "$name never answered; see .\bench.ps1 logs"
    return $false
}

switch ($Action) {

    'up' {
        Initialize-Env

        Write-Step 'Preparing the delivered dashboard for provisioning'
        python (Join-Path $root 'scripts\prepare-dashboard.py')

        Write-Step 'Starting the stack (the first run downloads ~2 GB)'
        # $LASTEXITCODE and not $? : docker writes its progress on stderr,
        # which PowerShell 5.1 wrongly reads as a failure.
        docker compose --project-directory $root up -d --wait --remove-orphans
        if ($LASTEXITCODE -ne 0) { throw "docker compose up failed (exit code $LASTEXITCODE)" }

        $ok = Wait-Service "$urlGrafana/api/health" 'Grafana (including the Infinity plugin install)'
        Wait-Service "$urlConsole/health" 'the console' 30 | Out-Null

        if ($ok) {
            Write-Host ''
            Write-Host "Console   : $urlConsole" -ForegroundColor Green
            Write-Host "Dashboard : $urlDashboard" -ForegroundColor Green
            Write-Host ''
            Write-Detail 'Open the console with: .\bench.ps1 console'
        }
    }

    'console'   { Start-Process $urlConsole }
    'dashboard' { Start-Process $urlDashboard }

    'scenario' {
        if (-not $Name -or $SCENARIOS -notcontains $Name) {
            Write-Host 'Available scenarios:' -ForegroundColor Yellow
            $SCENARIOS | ForEach-Object { Write-Host "    $_" }
            break
        }
        Write-Step "Applying scenario $Name"
        $state = Invoke-Console '/api/scenario' @{ name = $Name }
        Write-Detail ("bags={0} dwell={1} banner={2} phantoms/h={3}" -f `
            $state.derived.bags_in_system, $state.derived.avg_dwell_minutes, `
            $state.derived.expected_banner, $state.derived.phantoms_per_hour)
        Write-Detail 'The dashboard follows on its next refresh (5 s)'
    }

    'verify' {
        # Automated check: every scenario is applied, then both sources are
        # queried to confirm they tell the same story as the console.
        $expectations = @(
            @{ name = 'normal';         banner = 'OK';    active = 142; api = 200 },
            @{ name = 'morning_rush';   banner = 'OK';    active = 377; api = 200 },
            @{ name = 'system_jam';     banner = 'OK';    active = 577; api = 200 },
            @{ name = 'night_idle';     banner = 'IDLE';  active = 0;   api = 200 },
            @{ name = 'tracker_outage'; banner = 'STALE'; active = 142; api = 200 },
            @{ name = 'api_outage';     banner = 'OK';    active = 142; api = 503 }
        )

        function Get-SqlProbe {
            $password = (Get-Content (Join-Path $root '.env') |
                Where-Object { $_ -like 'MSSQL_SA_PASSWORD=*' }) -replace '^MSSQL_SA_PASSWORD=', ''
            $line = docker exec bhs-sqlserver /opt/mssql-tools18/bin/sqlcmd `
                -S localhost -U sa -P $password -C -d bhs -h -1 -W -b -i /sql/probe.sql
            return ($line | Select-Object -First 1).Trim() -split ';'
        }

        function Get-ApiStatus {
            try {
                $r = Invoke-WebRequest -Uri "http://localhost:$portApi/api/v1/status" `
                    -UseBasicParsing -TimeoutSec 5
                return [int]$r.StatusCode
            } catch {
                if ($_.Exception.Response) { return [int]$_.Exception.Response.StatusCode }
                return 0
            }
        }

        Write-Step 'Checking the scenarios (about 90 s)'
        Write-Host ('    {0,-16} {1,-8} {2,-8} {3,-8} {4}' -f 'SCENARIO', 'BANNER', 'ACTIVE', 'API', 'RESULT')
        $failures = 0

        foreach ($expected in $expectations) {
            Invoke-Console '/api/scenario' @{ name = $expected.name } | Out-Null
            Start-Sleep -Seconds 12
            $probe = Get-SqlProbe
            $status = Get-ApiStatus
            # The stock takes a few ticks to fill up: allow a small drift.
            $drift = [Math]::Abs([int]$probe[1] - $expected.active)

            if ($probe[0] -eq $expected.banner -and $drift -le 12 -and $status -eq $expected.api) {
                Write-Host ('    {0,-16} {1,-8} {2,-8} {3,-8} OK' -f $expected.name, $probe[0], $probe[1], $status) -ForegroundColor Green
            } else {
                Write-Host ('    {0,-16} {1,-8} {2,-8} {3,-8} FAILED (expected {4} / {5} / {6})' -f `
                    $expected.name, $probe[0], $probe[1], $status, $expected.banner, $expected.active, $expected.api) -ForegroundColor Red
                $failures++
            }
        }

        Write-Step 'Checking the phantom-bag defect (use case 1)'
        Invoke-Console '/api/scenario' @{ name = 'phantom_storm' } | Out-Null
        Start-Sleep -Seconds 8
        $before = [int](Get-SqlProbe)[2]
        Start-Sleep -Seconds 25
        $after = [int](Get-SqlProbe)[2]
        if ($after -gt $before) {
            Write-Host "    build-up $before -> $after phantoms       OK" -ForegroundColor Green
        } else {
            Write-Host "    build-up $before -> $after phantoms       FAILED" -ForegroundColor Red
            $failures++
        }

        Invoke-Console '/api/state' @{ phantom_bug = 'fixed' } | Out-Null
        Invoke-Console '/api/purge-phantoms' @{} | Out-Null
        Start-Sleep -Seconds 10
        $left = [int](Get-SqlProbe)[2]
        if ($left -eq 0) {
            Write-Host "    purge -> $left phantom left         OK" -ForegroundColor Green
        } else {
            Write-Host "    purge -> $left phantoms left        FAILED" -ForegroundColor Red
            $failures++
        }

        Invoke-Console '/api/scenario' @{ name = 'normal' } | Out-Null
        Write-Host ''
        if ($failures -eq 0) {
            Write-Host 'All green. Bench back to nominal.' -ForegroundColor Green
        } else {
            Write-Host "$failures check(s) failed." -ForegroundColor Red
        }
    }

    'status' {
        docker compose --project-directory $root ps

        Write-Step 'Console'
        try {
            $state = Invoke-RestMethod -Uri "$urlConsole/api/state" -TimeoutSec 5
            Write-Detail ("scenario={0} rate={1} b/h dwell={2} min bags={3} banner={4}" -f `
                $state.settings.scenario, $state.settings.arrival_rate, `
                $state.settings.dwell_minutes, $state.derived.bags_in_system, `
                $state.derived.expected_banner)
        } catch {
            Write-Warning "Console unreachable: $($_.Exception.Message)"
        }

        Write-Step 'Mocked API'
        try {
            $status = Invoke-RestMethod -Uri "http://localhost:$portApi/api/v1/status" -TimeoutSec 5
            Write-Detail "bags_in_system=$($status.bags_in_system) avg_dwell=$($status.avg_dwell_minutes) last_update=$($status.last_update)"
        } catch {
            Write-Detail "API in simulated outage, or unreachable: $($_.Exception.Message)"
        }

        Write-Step 'SQL state (queries 1, 4 and 5 of queries.sql)'
        try { Invoke-Sql 'inspect.sql' } catch { Write-Warning $_.Exception.Message }
    }

    'test' {
        Write-Step 'Unit tests of the simulation model'
        python -m pytest (Join-Path $root 'tests') -q
    }

    'package' {
        # Self-contained copy: no dependency left on the repository, so the
        # bench can be dropped anywhere.
        $target = Join-Path $root 'dist\test-bench'
        Write-Step "Self-contained copy into $target"

        if (Test-Path (Join-Path $root 'dist')) {
            Remove-Item (Join-Path $root 'dist') -Recurse -Force
        }
        New-Item -ItemType Directory -Path $target -Force | Out-Null

        foreach ($item in @('console', 'mock-api', 'sql', 'grafana\provisioning',
                            'scripts', 'tests', 'docker-compose.yml',
                            'bench.ps1', 'bench.sh',
                            '.env.example', 'README.md')) {
            $source = Join-Path $root $item
            if (-not (Test-Path $source)) { continue }
            $destination = Join-Path $target $item
            $parent = Split-Path $destination -Parent
            if (-not (Test-Path $parent)) { New-Item -ItemType Directory -Path $parent -Force | Out-Null }
            Copy-Item $source $destination -Recurse -Force
        }

        # The delivered dashboard travels with the bench: prepare-dashboard.py
        # falls back on it once the use case 2 folder is no longer next door.
        $dashboard = Join-Path $root '..\use-case-2-dashboard\solution\dashboard.json'
        if (Test-Path $dashboard) {
            New-Item -ItemType Directory -Path (Join-Path $target 'dashboard') -Force | Out-Null
            Copy-Item $dashboard (Join-Path $target 'dashboard\bhs-controlroom.source.json') -Force
            Write-Detail 'dashboard.json embedded'
        }

        Write-Detail 'Neither .env nor state/ is copied: both get regenerated.'
        Write-Host ''
        Write-Host "Ready: $target" -ForegroundColor Green
        Write-Detail 'Run .\bench.ps1 up there, exactly as here.'
    }

    'logs' {
        docker compose --project-directory $root logs --tail 60
    }

    'stop' {
        Write-Step 'Pausing (data is kept)'
        docker compose --project-directory $root stop
        Write-Detail 'Resume with: .\bench.ps1 start'
    }

    'start' {
        Write-Step 'Resuming the stack'
        # init is deliberately left out: it has already done its job, running
        # it again would re-seed the database for nothing.
        docker compose --project-directory $root start sqlserver mock-api console simulator grafana
        Wait-Service "$urlConsole/health" 'the console' 45 | Out-Null
        Write-Host "Console   : $urlConsole" -ForegroundColor Green
        Write-Host "Dashboard : $urlDashboard" -ForegroundColor Green
    }

    'down' {
        Write-Step 'Stopping the stack and dropping the volumes'
        docker compose --project-directory $root down -v
    }
}
